<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<?php echo $this->form()->closeTag() ?>
<div class="row">    
  <div class="col-sm-4"> 
      <?php
      $select = $form->get('idEmp');
      echo $formLabel->openTag().'Buscar empleado';
      echo $formLabel->closeTag();
      echo $this->formSelect($select);
      echo $this->formElementErrors($select);
      ?>
  </div>    
  <div class="col-sm-2"><br />              
      <?php echo $this->formElement($form->get('buscar')) ?>
  </div>
</div>    
<div id='resultado'></div>

<script>  
 $(function (){     
     $('#submitbutton').click(function(){ 
       var idEmp   = $("#idEmp").val();  
       if (idEmp=='')   
       {
          alert('Debe seleccionar a algun empleado')    
          return false;
       }
       var parametros = {
            "idEmp"   : idEmp,
       };         
       $.ajax({
             data:  parametros,     
             type:  'post',
             url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>ag',
             beforeSend: function () {
                 $("#resultado").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>Recalculando por favor espere...');
             },
              success:  function (response) {
                 $("#resultado").html(response);  
                 //   alert("Cuotas registradas de forma correcta")
              }
         }); // Fin ajax                                                                                       

       
     });
 })
</script> 


<?php echo $this->render('layout/iregresar') ?>    

