<div class="sidebar-shortcuts" id="sidebar-shortcuts">
  <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
     <a href="<?php echo $this->basePath()."/" ?>infcentral/dastalento/list" class="btn btn-success"><span class="ace-icon fa fa-bar-chart-o"></span>
     </a>                                            
                                            
   <button class="btn btn-info">
							<i class="ace-icon fa fa-pencil"></i>
						</button>

	<!-- #section:basics/sidebar.layout.shortcuts -->
	<a href="<?php echo $this->basePath()."/" ?>infcentral/bitacora/list" class="btn btn-warning"><span class="ace-icon fa fa-users"></span></a>

	<a href="<?php echo $this->basePath()."/" ?>talentohumano/programa/list/1.1" class="btn btn-danger"><span class="ace-icon fa fa-calendar"></span></a>
						
						<!-- /section:basics/sidebar.layout.shortcuts -->
    </div>
</div><!-- /.sidebar-shortcuts -->

                                