<script type="text/javascript" src="<?php echo $this->basePath()."/" ?>/charts/amcharts.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath()."/" ?>/charts/pie.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath()."/" ?>/charts/serial.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath()."/" ?>/charts/gauge.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath()."/" ?>/charts/plugins/export/export.js"></script>

<script type="text/javascript" src="<?php echo $this->basePath()."/" ?>/charts/radar.js"></script>

<link type="text/css" href="<?php echo $this->basePath()."/" ?>/charts/plugins/export/export.css" rel="stylesheet">




                                
                                