
<!-- Styles -->
<style>

.amcharts-export-menu-top-right {
  top: 10px;
  right: 0;
}
</style>

<!-- Chart code -->
<script>
var chart = AmCharts.makeChart("<?php echo $this->grafico; ?>", {
  "type": "serial",
  "theme": "light",
  "marginRight": 70,
  "dataProvider": [ <?php echo $this->consulta; ?> ],
  "startDuration": 1,
  "graphs": [{
    "balloonText": "<b>[[category]]: [[value]]</b>",
    "fillColorsField": "color",
    "fillAlphas": 0.9,
    "lineAlpha": 0.2,
    "type": "column",
    "valueField": "valor<?php echo $this->gra?>",
  }],
  "chartCursor": {
    "categoryBalloonEnabled": false,
    "cursorAlpha": 0,
    "zoomable": false
  },
  "categoryField": "campo<?php echo $this->gra?>",
  "categoryAxis": {
    "gridPosition": "start",
    "labelRotation": 45
  },
  "export": {
    "enabled": true
  }

});
</script>

<!-- HTML -->
<div id="<?php echo $this->grafico; ?>" style="width:100%; height:500px;"></div>
