                    <div class="infobox infobox-chart">
                      <!-- #section:pages/dashboard.infobox.sparkline -->
                      <div class="infobox-icon">
                        <i class="ace-icon fa fa-plus-square"></i>
                      </div>

                      <!-- /section:pages/dashboard.infobox.sparkline -->
                      <div class="infobox-data">
                        <span class="infobox-data-number"><?php echo $this->num ?></span>
                        <div class="infobox-content"><?php echo $this->titCuadro ?></div>
                      </div>

                      <div class="badge badge-alert">
                        <i class="ace-icon fa fa-arrow-up"></i>
                      </div>


                    </div>